In [1]:
import torch
import numpy as np


In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [85]:
npa=np.array(data)
x_np=torch.tensor(npa)

In [86]:
x_np[0,0]=-9
print(npa)
x_np

[[1 2]
 [3 4]]


tensor([[-9,  2],
        [ 3,  4]], dtype=torch.int32)

In [6]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [8]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.1534, 0.3196],
        [0.1413, 0.2858]])

In [16]:
torch.rand_like(x_data,dtype=torch.float)

tensor([[0.2704, 0.4348],
        [0.7928, 0.3686]])

In [28]:
shape=(2,3)
torch.rand(shape)

tensor([[0.6353, 0.0230, 0.0120],
        [0.1922, 0.8552, 0.8484]])

In [31]:
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [37]:
tnt=torch.rand(3,4)

In [40]:
tnt.dtype

torch.float32

In [42]:
tnt.device
tnt.shape

torch.Size([3, 4])

In [44]:
f=np.random.randn(2,3)
f

array([[0.42937544, 2.92275254, 0.29222072],
       [0.81072679, 0.80767071, 0.67343453]])

In [45]:
f_t=torch.tensor(f)
f_t

tensor([[0.4294, 2.9228, 0.2922],
        [0.8107, 0.8077, 0.6734]], dtype=torch.float64)

In [47]:
f[:,0].shape

(2,)

In [49]:
g=np.random.randn(2,3,3)

In [50]:
g

array([[[ 1.26266086,  0.75357994, -0.07021182],
        [ 0.37475508,  0.01352844,  0.5503734 ],
        [ 1.26520848, -0.86322601,  1.57125082]],

       [[-0.95707136, -0.7341658 ,  0.74163095],
        [-1.82959922,  0.03472061,  0.07863003],
        [ 2.00072134,  1.06651647,  0.88663415]]])

In [51]:
g[:,0]

array([[ 1.26266086,  0.75357994, -0.07021182],
       [-0.95707136, -0.7341658 ,  0.74163095]])

In [52]:
g[:,:,0]

array([[ 1.26266086,  0.37475508,  1.26520848],
       [-0.95707136, -1.82959922,  2.00072134]])

In [54]:
g[:,0,1].shape

(2,)

In [57]:
f_t.shape


torch.Size([2, 3])

In [58]:
f2=torch.cat([f_t,f_t],dim=1 )

In [59]:
f2

tensor([[0.4294, 2.9228, 0.2922, 0.4294, 2.9228, 0.2922],
        [0.8107, 0.8077, 0.6734, 0.8107, 0.8077, 0.6734]], dtype=torch.float64)

In [63]:
tensor= torch.rand(4,4)
tensor

tensor([[0.3884, 0.4374, 0.8579, 0.1447],
        [0.5484, 0.7114, 0.9389, 0.0263],
        [0.9594, 0.2848, 0.9507, 0.1526],
        [0.9179, 0.5452, 0.0141, 0.3829]])

In [64]:
y1= tensor @ tensor.T

In [65]:
y1

tensor([[1.0990, 1.3334, 1.3348, 0.6625],
        [1.3334, 1.6891, 1.6253, 0.9146],
        [1.3348, 1.6253, 1.9286, 1.1078],
        [0.6625, 0.9146, 1.1078, 1.2866]])

In [66]:
y2=tensor.matmul(tensor.T)
y2

tensor([[1.0990, 1.3334, 1.3348, 0.6625],
        [1.3334, 1.6891, 1.6253, 0.9146],
        [1.3348, 1.6253, 1.9286, 1.1078],
        [0.6625, 0.9146, 1.1078, 1.2866]])

In [67]:
y3=torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[1.0990, 1.3334, 1.3348, 0.6625],
        [1.3334, 1.6891, 1.6253, 0.9146],
        [1.3348, 1.6253, 1.9286, 1.1078],
        [0.6625, 0.9146, 1.1078, 1.2866]])

In [68]:
z1=tensor*tensor
z1

tensor([[1.5082e-01, 1.9131e-01, 7.3592e-01, 2.0929e-02],
        [3.0072e-01, 5.0615e-01, 8.8150e-01, 6.9329e-04],
        [9.2036e-01, 8.1105e-02, 9.0379e-01, 2.3289e-02],
        [8.4258e-01, 2.9719e-01, 2.0016e-04, 1.4664e-01]])

In [70]:
z2=tensor.mul(tensor)
z2

tensor([[1.5082e-01, 1.9131e-01, 7.3592e-01, 2.0929e-02],
        [3.0072e-01, 5.0615e-01, 8.8150e-01, 6.9329e-04],
        [9.2036e-01, 8.1105e-02, 9.0379e-01, 2.3289e-02],
        [8.4258e-01, 2.9719e-01, 2.0016e-04, 1.4664e-01]])

In [71]:
agg=tensor.sum()

In [72]:
agg

tensor(8.2609)

In [73]:
d=agg.item()

In [75]:
type(d)

float

In [76]:
print(type(d))

<class 'float'>


In [77]:
print(tensor)
tensor.add_(3)
print(tensor)

tensor([[0.3884, 0.4374, 0.8579, 0.1447],
        [0.5484, 0.7114, 0.9389, 0.0263],
        [0.9594, 0.2848, 0.9507, 0.1526],
        [0.9179, 0.5452, 0.0141, 0.3829]])
tensor([[3.3884, 3.4374, 3.8579, 3.1447],
        [3.5484, 3.7114, 3.9389, 3.0263],
        [3.9594, 3.2848, 3.9507, 3.1526],
        [3.9179, 3.5452, 3.0141, 3.3829]])


In [78]:
tensor.t_()

tensor([[3.3884, 3.5484, 3.9594, 3.9179],
        [3.4374, 3.7114, 3.2848, 3.5452],
        [3.8579, 3.9389, 3.9507, 3.0141],
        [3.1447, 3.0263, 3.1526, 3.3829]])

In [79]:
tensor

tensor([[3.3884, 3.5484, 3.9594, 3.9179],
        [3.4374, 3.7114, 3.2848, 3.5452],
        [3.8579, 3.9389, 3.9507, 3.0141],
        [3.1447, 3.0263, 3.1526, 3.3829]])

In [80]:
v=tensor.numpy()
print(v)

[[3.3883617 3.5483825 3.9593563 3.917919 ]
 [3.4373922 3.711441  3.284789  3.5451546]
 [3.8578563 3.9388819 3.9506812 3.0141478]
 [3.1446671 3.0263305 3.1526065 3.3829403]]


In [81]:
t.add_(1)

NameError: name 't' is not defined

In [82]:
tensor.add_(1)

tensor([[4.3884, 4.5484, 4.9594, 4.9179],
        [4.4374, 4.7114, 4.2848, 4.5452],
        [4.8579, 4.9389, 4.9507, 4.0141],
        [4.1447, 4.0263, 4.1526, 4.3829]])

In [83]:
v

array([[4.388362 , 4.5483828, 4.9593563, 4.917919 ],
       [4.437392 , 4.711441 , 4.284789 , 4.5451546],
       [4.8578563, 4.938882 , 4.950681 , 4.0141478],
       [4.144667 , 4.0263305, 4.1526065, 4.3829403]], dtype=float32)

In [88]:
g=np.random.randn(4,5)

In [89]:
g

array([[ 2.24165796,  0.75637395,  1.0977243 ,  0.78153287, -0.68261304],
       [ 0.35505666,  0.61860565,  0.41466459, -0.76288306, -0.80351349],
       [-0.05208719,  0.25324731,  2.13123498, -0.45031568,  0.10117564],
       [ 0.84659545, -1.71948947, -0.86305372, -1.08588658, -0.11509593]])

In [91]:
t=torch.from_numpy(g)

In [92]:
t

tensor([[ 2.2417,  0.7564,  1.0977,  0.7815, -0.6826],
        [ 0.3551,  0.6186,  0.4147, -0.7629, -0.8035],
        [-0.0521,  0.2532,  2.1312, -0.4503,  0.1012],
        [ 0.8466, -1.7195, -0.8631, -1.0859, -0.1151]], dtype=torch.float64)

In [93]:
t[0,0]=769999

In [94]:
g

array([[ 7.69999000e+05,  7.56373955e-01,  1.09772430e+00,
         7.81532869e-01, -6.82613036e-01],
       [ 3.55056657e-01,  6.18605648e-01,  4.14664592e-01,
        -7.62883062e-01, -8.03513494e-01],
       [-5.20871854e-02,  2.53247312e-01,  2.13123498e+00,
        -4.50315679e-01,  1.01175640e-01],
       [ 8.46595449e-01, -1.71948947e+00, -8.63053715e-01,
        -1.08588658e+00, -1.15095929e-01]])